// Code generated by "stringer -type=FaultType"; DO NOT EDIT.

package soldr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NA-1]
	_ = x[FieldLevel-2]
	_ = x[RequestLevel-4]
}

const (
	_FaultType_name_0 = "NAFieldLevel"
	_FaultType_name_1 = "RequestLevel"
)

var (
	_FaultType_index_0 = [...]uint8{0, 2, 12}
)

func (i FaultType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FaultType_name_0[_FaultType_index_0[i]:_FaultType_index_0[i+1]]
	case i == 4:
		return _FaultType_name_1
	default:
		return "FaultType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
